// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {

		int n = Integer.parseInt(args[0]);

		int countAbove = 0;
		int countUnder = 0; 

		for (int i = 0; i<n ;i++ ){
			double r1 = Math.random();
			if (r1>0.5) {countAbove = countAbove+1;}
		    else if (r1 <=0.5){ countUnder = countUnder+1;}
		}
    
    System.out.println("> 0.5:  " + countAbove + " times");
	System.out.println("<= 0.5: " + countUnder + " times");

		if (countUnder>0){System.out.println("Ratio:  " + (double)countAbove/countUnder);}

	
		}
	}
